name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3' # Or your desired Python version
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Running ls ."
        ls .
        echo "Running cat requirements.txt"
        cat requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: ./run_tests.sh

  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master